name: helpdesk_flutter_getx_retrofit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5

  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.8.1

  flutter_secure_storage: ^8.0.0
  http_status_code: ^0.0.2
  pretty_dio_logger: ^1.3.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1

  retrofit_generator: '>=7.0.0 <8.0.0'   #// required dart >=2.19
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

